### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by mingodad** [codinuum/cca#42]
While trying to build on Ubuntu 18.04 with `version 4.11.2`:
```
make
for d in util mldiff otreediff ast; do \
  if ! make -k -C $d; then \
    break; \
  fi \
done
...
ocamlfind ocamlopt -package unix,camlzip,cryptokit,netzip,netstring,pxp,volt -syntax camlp4o -ppopt -level -ppopt WARN  -O3 -g -c xstring.ml
File "xstring.ml", line 50, characters 22-40:
50 | let startswith s s0 = String.starts_with ~prefix:s0 s
                           ^^^^^^^^^^^^^^^^^^
Error: Unbound value String.starts_with
../rules.mk:105: recipe for target 'xstring.cmx' failed
make[1]: *** [xstring.cmx] Error 2
...
ocamlfind ocamlopt -package unix,camlzip,cryptokit,netzip,netstring,pxp,volt  -O3 XML.mli
File "XML.mli", line 37, characters 2-21:
37 |   Xchannel.in_channel -> 'a Pxp_document.document
       ^^^^^^^^^^^^^^^^^^^
Error: Unbound module Xchannel
../rules.mk:108: recipe for target 'XML.cmi' failed
make[1]: *** [XML.cmi] Error 2
...
```

**Comment by codinuum** [comment]
Sorry for the inconvenience. The latest cca requires ocaml (>= 4.14.0 & < 5.0.0).
We will update README.md soon...
